var tl=gsap.timeline()
        tl.to('.namingbox',{
            scale:1
        })
        .to('.anibox4',{
            y:0,
            duration:0.3,
        })
        .to('.anibox3',{
            y:0,
            duration:0.3,
        })
        .to('.anibox2',{
            y:0,
            duration:0.3,
        })
        .to('.anibox1',{
            y:0,
            duration:0.3,
        });